title: Next Generation Medicine Lab
description: Next Genernation Medicine Lab (NEXGEM) aims to integrate the biological big-data with AI and data science approaches and cutting-edge experimental techniques to find a better way to treat cancer patients. Our research covers highly translationally important questions in multiple fields of cancer biology including cancer immunotherapy. In particular, we focus on precision cancer medicine, tailoring the cancer treatments based on the molecular markup of individual patients from the perspective of AI and data science.
header: images/background.jpg
footer: images/background.jpg
links:
  email: lee.joosang@gmail.com
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: https://github.com/nexgem
  twitter: YourLabHandle
  youtube: YourLabChannel
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: members
    values:
      layout: member
  - scope:
      type: posts
    values:
      layout: post
collections:
  members:
    output: true
  posts:
    output: true
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
highlighter: rouge
theme: null
sass:
  sass_dir: _styles
include:
  - _styles
  - _scripts
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
email: lee.joosang@gmail.com
github: nexgem

